import express from 'express';
import { signup } from '../controller/user.controller.js';
import{login} from"../controller/user.controller.js";
import{auth} from '../controller/user.controller.js';
import { verifyToken } from '../middleware/verify.js';
const router=express.Router();
router.post('/signup',signup);
router.post('/login',login);
router.get('/auth',auth);
export default router;